config/routes.rb
HzchrisApp::Application.routes.draw do
  resources :photos

  resources :events
  get "static_pages/home"
  root 'static_pages#home'
  resources :samples
  match '/input-name', to: 'homeworks#input_name', via: 'get',    as: :input_name
  match '/hello', to: 'homeworks#hello', via: 'post'
  match '/find-prime', to: 'homeworks#find_prime', via: 'get',    as: :find_prime
  match '/show-prime', to: 'homeworks#show_prime', via: 'post',   as: :show_prime
  match '/about', to: 'homeworks#about', via: 'get'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>",
                                         :small => "150x150",
                                         :thumb => "100x100>" }
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  has_secure_password
  before_save { email.downcase! }
  validate :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :find_event, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = Event.page(params[:page]).per(5)
  end

  def show

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:success] = "Event was successfully created!"
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @event.update_attributes(event_params)
      flash[:success] = "Event was successfully updated!"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Event was successfully deleted!"
    redirect_to action: :index
  end


  # Below manipulate Strong Parameters
  private

    def event_params
      params.require(:event).permit(:name, :description)
    end


  protected
    def find_event
      @event = Event.find(params[:id])
    end

end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  
  def input
  end

  def hello
  end

  def show_prime
    number = params[:number].to_i

    if number <= 1 || number > 100000 
      @err = "Invalid input! (input must be > 1 and <= 100000)"
      return @err

    else
      @prime = Rails.cache.read(number)

      unless @prime.nil?
        return @prime

      else
        num = number

        while num > 2
          for i in 2..num / 2
            if num % i == 0
              break

            elsif (num % i != 0) && (i == num/2)
              Rails.cache.write(number, num)
              @prime = num
              return @prime
            end
          end
          num = num - 1
        end
      end
    end
  end

  def about
    
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create(photo_params)

    redirect_to action: :index
  end
end

  private
    def photo_params
      params.require(:photo).permit(:image)
    end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/_form.html.erb
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_area :description %>

app/views/events/edit.html.erb
<h1><%= @event.name %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @event, url: { controller: 'events', action: 'update', id: @event } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<h1>Events</h1>

<div class="row">
  <div class="span6 offset3">
    <p>Below are events list</p>
    <ul>
    <% @events.each do |event| %>
      <li>
        <strong><%= event.name %></strong>
        <%= link_to 'Show', event_path(event) %>

        <%= link_to 'Edit', edit_event_path(event) %>

        <%= link_to 'Delete', event_path(event), method: 'delete' %>
      </li>
    <% end %>
    <%= paginate @events %>
    </ul>
    <%= button_to 'New event', new_event_path, method: 'get', class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @event, url: { controller: 'events', action: 'create' } do |f| %>
      
      <%= render partial: 'form', locals: { f: f } %>

      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= simple_format(@event.description) %>

    <%= link_to 'Back to events list', events_path %>
  </div>
</div>

app/views/homeworks/about.html.erb
<h1>About</h1>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3 text-center">
      <h5>洪梓凱(HzChris)</h5>
      <div class="pagination-centered lead">
        <%= image_tag "hzchris.jpg", class: "img-circle", 
                                     style: "width: 140px; align: center" %>
      </div>
      <small>
        政治大學資訊管理研究所</br>
        National ChengChi University
        Department of Management Information Systems</br>
        Email: <a href="mailto:hzchirs@gmail.com">hzchris@gmail.com</a>
      </small>
    </div>
    <div class="span9">
      <p>
        Hi，我是梓凱，台中人，目前於政治大學就讀資管所。<br>
        興趣是打桌球、彈吉他、慢跑等等。<br>
        目前正在學習Ruby on Rails這個有趣的框架，如果你也有興趣，歡迎互相交流。
      </p>
      <ul>
        <li><a href="https://www.facebook.com/hzchirs" target="_blank">Facebook</a></li>
        <li><a href="http://hzchirs-blog.logdown.com/" target="_blank">Blog</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/homeworks/find_prime.html.erb
<h1>Input User</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_tag show_prime_path, method: 'post' do %>

      <%= label_tag :number, 'Input a number here' %>
      <%= text_field_tag :number %>
      
      <%= submit_tag 'Input', class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/homeworks/hello.html.erb
<h1>Show User</h1>

<div class="row">
  <div class="span6 offset3">
    <p><%= "Hello!  #{params[:name]}!" %></p>
    <%= link_to 'Back to Home', root_path %>
  </div>
</div>

app/views/homeworks/input_name.html.erb
<h1>Input User</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_tag hello_path, method: 'post' do %>

      <%= label_tag :name, 'Input your name here' %>
      <%= text_field_tag :name %>
      
      <%= submit_tag 'Input', class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/homeworks/show_prime.html.erb
<h1>Show The Biggest Prime</h1>

<div class="row">
  <div class="span6 offset3">
  <% if @prime %>
    <p><%= "The biggest prime of #{params[:number]} is #{@prime}" %></p>
  <% else %>
    <p><%= @err %></p>
  <% end %>
    <%= link_to 'Back to Home', root_path %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "HzChris app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    '#' %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HzChris Application</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/photos/index.html.erb
<h1>Photos</h1>

<div class="row">
  <div class="span6 offset3">
    <% @photos.each do |photo| %>
      <%= image_tag photo.image.url(:small), class: "img-rounded" %>
    <% end %>

    <%= link_to 'New photos', new_photo_path %>
  </div>
</div>

app/views/photos/new.html.erb
<h1>Upload Photo</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @photo do |f| %>
      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= submit_tag "Upload", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/samples/new.html.erb
<h1>Create User</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :account %>
      <%= f.text_field :account %>

      <%= f.lable :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation %>

    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<h1>Welcome to HzChris Web Application!</h1>
<div class="row-fluid">
  <div class="span6 offset3">
    <p>Here are some applications available. Please choose one which you intrested in.</p>
    <ul>
      <li><%= link_to "Show your name", input_name_path %></li>
      <li><%= link_to "Find the biggest Prime", find_prime_path %></li>
      <li><%= link_to "Self Introduction", about_path %></li>
      <li><%= link_to "Upload images", photos_path %></li>
      <li><%= link_to "ihower demo", events_path %></li>
    </ul>
  </div>
  
</div>